#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
PLOTTING: plotting functions for volume visualization
16 nov 2021
@author: sama ahmed

[ ] get rid of prettyaxes class, use functions instead
"""

import matplotlib.pyplot as plt
import os
import logging

LOG = logging.getLogger(__name__)


def plot_slice(frame, fig=None, ax=None):
    """plot one frame of volume"""
    fig, ax = _get_fig_and_ax(fig, ax)

    im = ax.imshow(frame.T,
                   cmap='Greys_r')
    ax.axis('off')
    PrettyAxes()
    return ax, im


class PrettyAxes:
    """prettify figs generated by matplotlib
    """

    def __init__(self, fig=None, ax=None, autoPretty=True):
        fig, ax = _get_fig_and_ax(fig, ax)

        self.fig = fig
        self.ax = ax

        if autoPretty:
            self.prettify()

    def prettify(self):
        """automatically run the baseline prettification"""
        self.remove_fig_borders()
        self.adjust_fonts()
        self.place_ylabel()

    def remove_fig_borders(self, rmAll=False):
        """remove top and right borders box around figure"""
        self.ax.spines['top'].set_visible(False)
        self.ax.spines['right'].set_visible(False)

        if rmAll:
            self.ax.spines['bottom'].set_visible(False)
            self.ax.spines['left'].set_visible(False)

    def adjust_fonts(self, fontsize=8):
        """adjust fontsize for fig"""
        plt.xticks(fontsize=fontsize)
        plt.yticks(fontsize=fontsize)

    def place_ylabel(self, x=-0.1, y=0.5):
        """better placement for y-label"""
        self.ax.get_yaxis().set_label_coords(x, y)


# -- helpers --
def _get_fig_and_ax(fig, ax):
    fig = fig if fig is not None else plt.gcf()
    ax = ax if ax is not None else plt.gca()
    return fig, ax


def save_fig(figdir: str, figname: str):
    """save current fig"""
    LOG.info(f"saving current figure to: {os.path.join(figdir, figname)}")
    plt.savefig(os.path.join(figdir, figname),
                transparent=True,
                bbox_inches='tight')
